import LegalLayout from "./LegalLayout";

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service" updated="June 26, 2025">
      <p>
        By using LetsConnect (&quot;the Service&quot;), you agree to these Terms of Service. If you
        do not agree, do not use the Service.
      </p>

      <h2>Description of service</h2>
      <p>
        LetsConnect is a tool that connects your Gmail account to Slack and an AI assistant so you can
        ask questions about your email in chat. You must connect accounts voluntarily via OAuth.
      </p>

      <h2>Eligibility</h2>
      <p>
        You must be at least 18 years old and have the authority to connect the Gmail and Slack
        accounts you link to the Service.
      </p>

      <h2>Your responsibilities</h2>
      <ul>
        <li>Keep your login credentials secure.</li>
        <li>Only connect accounts you are authorized to use.</li>
        <li>Use the Service in compliance with Google&apos;s and Slack&apos;s terms of service.</li>
        <li>Do not use the Service for spam, abuse, or unlawful purposes.</li>
      </ul>

      <h2>AI-generated responses</h2>
      <p>
        Replies are generated by AI (Google Gemini) and may be inaccurate. Always verify important
        information before acting on it, especially before sending email or making decisions based on
        summaries.
      </p>

      <h2>Third-party services</h2>
      <p>
        The Service integrates with Gmail, Slack, and Google Gemini. Your use of those services is
        subject to their respective terms and privacy policies. We are not responsible for third-party
        services.
      </p>

      <h2>Availability</h2>
      <p>
        The Service is provided &quot;as is&quot; without warranties. We may modify, suspend, or
        discontinue features at any time.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, LetsConnect and its operators are not liable for any
        indirect, incidental, or consequential damages arising from your use of the Service.
      </p>

      <h2>Termination</h2>
      <p>
        You may stop using the Service at any time by disconnecting integrations and deleting your
        account. We may suspend access if you violate these terms.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms. Continued use after changes constitutes acceptance of the updated
        terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms:{" "}
        <a href="mailto:gauravdewli1970@gmail.com">gauravdewli1970@gmail.com</a>
      </p>
    </LegalLayout>
  );
}
